### PR TITLE
Fix build with Qt 5.11

### PR DESCRIPTION
**Pull request by a17r**
Upgrade to Qt 5.11 causes failing packages everywhere because of internal header cleanup, this commit is fixing scantailor-advanced.

### CODE REVIEW

**Comment by 4lex4** [comment]
I've slightly changed your commit please check whether STA is built now. (Clone STA from [develop branch](https://github.com/4lex4/scantailor-advanced/tree/develop))

**Comment by a17r** [comment]
I see you moved the headers into cpp files, that will require more changes:

```
/var/tmp/portage/media-gfx/scantailor-advanced-9999/work/scantailor-advanced-9999/filters/page_split/OptionsWidget.cpp:40:38: error: invalid use of incomplete type ‘class QButtonGroup’
     auto* grp = new QButtonGroup(this);
```

**Comment by a17r** [comment]
Confirmed, your 'develop' built fine now against Qt-5.11_beta3.

**Comment by 4lex4** [comment]
**a17r**, ty for your work.

**Comment by maelvalais** [comment]
Merge? 🤔
